// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYrFkMIJAPRjpFY6TYK5dN0xu8H6dG3uk',
    appId: '1:401646790851:web:3b2fcf5f41c1857b315a76',
    messagingSenderId: '401646790851',
    projectId: 'iaapp-eebe3',
    authDomain: 'iaapp-eebe3.firebaseapp.com',
    storageBucket: 'iaapp-eebe3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjKUJN1Ii15pFNOj5-e29bVFUYKoekDE',
    appId: '1:401646790851:android:52cc72b8436f7958315a76',
    messagingSenderId: '401646790851',
    projectId: 'iaapp-eebe3',
    storageBucket: 'iaapp-eebe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MAUqYvUdXX7yMHwnavlK7ueohVuPVco',
    appId: '1:401646790851:ios:b50dcbb74eb723b8315a76',
    messagingSenderId: '401646790851',
    projectId: 'iaapp-eebe3',
    storageBucket: 'iaapp-eebe3.appspot.com',
    iosBundleId: 'com.example.mobileAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MAUqYvUdXX7yMHwnavlK7ueohVuPVco',
    appId: '1:401646790851:ios:eba1be28c98ff469315a76',
    messagingSenderId: '401646790851',
    projectId: 'iaapp-eebe3',
    storageBucket: 'iaapp-eebe3.appspot.com',
    iosBundleId: 'com.example.mobileAi.RunnerTests',
  );
}
